#! /bin/sh
### BEGIN INIT INFO
# Provides:          mediaplat
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: MediaPlat Server
# Description:       MediaPlat Server for LG NAS
### END INIT INFO

# Do NOT "set -e"

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="MediaPlat server"
NAME=mediaplat
DAEMON=/usr/bin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

. /var/lib/mediaplat/mediaplat

do_start() {
  mediaplat_start
}

do_stop() {
  mediaplat_stop
}

do_monitor() {
  LOG1=/var/log/postgresql/postgresql-9.1-main.log
  LOG2=/var/log/nginx/nginx.log
  LOG3=/var/log/mediaplat/mediaplat.log
  WCOUNT=3

  mkdir -p $(dirname $LOG1) $(dirname $LOG2) $(dirname $LOG3)
  touch $LOG1 $LOG2 $LOG3

  TEMP_FILE=/var/run/screeen.size
  dialog --print-maxsize 2> $TEMP_FILE
  HEIGHT=$(cat $TEMP_FILE | cut -d " " -f 2 | tr -d ",")
  WIDTH=$(cat $TEMP_FILE | cut -d " " -f 3)
  HEIGHT_ONE=$(expr $HEIGHT / $WCOUNT - 1)
  WIDTH_ONE=$(expr $WIDTH - 2)

  dialog \
    --begin 1 1 --no-shadow --ascii-lines --title "$LOG1" \
    --tailboxbg $LOG1 $HEIGHT_ONE $WIDTH_ONE \
    --and-widget \
    --begin $(expr 2 + $HEIGHT_ONE) 1 --no-shadow --ascii-lines --title "$LOG2" \
    --tailboxbg $LOG2 $HEIGHT_ONE $WIDTH_ONE \
    --and-widget \
    --begin $(expr 3 + $HEIGHT_ONE + $HEIGHT_ONE) 1 --no-shadow --ascii-lines --title "$LOG3" \
    --tailboxbg $LOG3 $HEIGHT_ONE $WIDTH_ONE \
    --and-widget \
    --begin 0 0 --no-shadow --msgbox "" 1 1
}

case "$1" in
  start)
    do_start
	;;
  stop)
    do_stop
	;;
  restart|force-reload)
    do_stop
	do_start
	;;
  monitor)
    do_monitor
	;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac
